name: 'git-chaos'
author: 'chaos-monkeys'
description: 'Generate structured chaos for your repository'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      Auth token used to fetch the repository. The token is stored in the local
      git config, which enables your scripts to run authenticated git commands.
      The post-job step removes the token from the git config. [Learn more about
      creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  AWS_ACCESS_KEY:
    description: 'AWS Access Key Credential'
  AWS_SECRET_KEY:
    description: 'AWS Secret Key Credential'
runs:
  using: node12
  main: dist/index.js
